import type { Metadata } from "next";
import { Montserrat } from 'next/font/google';
import { Menu4Layout } from "./_components/Menu4Layout";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "react-query";

const montserrat = Montserrat({
  subsets: ['latin'],
  style: ['normal', 'italic'],
  weight: ['400', '700'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased flex bg-gray-300`}>
        <Menu4Layout />
          {children}
      </body>
    </html>
  );
}
